
all:
  hosts:
    johweb-ec2-pub1:
      ansible_host: "{{ lookup('env', 'host_ip') }}"
      ansible_user: "{{ lookup('env', 'websrv_usr') }}"
     # ansible_ssh_private_key_file: {{ lookup('env', 'TF_VAR_the_key') }}

  vars:
    #ansible_user: your_username
    ansible_ssh_private_key_file: "{{ lookup('env', 'TF_VAR_the_key') }}"
