
all:
  hosts:
    johweb-ec2-pub1:
      ansible_host: "{{ lookup('env', 'HOST_IP') }}"
      ansible_user: "{{ lookup('env', 'WEBSRV_USR') }}"
     # ansible_ssh_private_key_file: {{ lookup('env', 'TF_VAR_the_key') }}

  vars:
    #ansible_ssh_private_key_file: "{{ lookup('env', 'TF_VAR_THE_KEY') }}"
    #ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q 3.144.253.181"'
    ansible_ssh_common_args: "-J '{{ lookup('env', 'WEBSRV_USR') }}'@'{{ lookup('env', 'BASTION_IP') }}'"               #ssh ec2-user@10.0.10.165 -J ec2-user@18.222.23.137
