- name: Check if Docker is installed
  hosts: johweb-ec2-pub1
  become: yes
  gather_facts: no
  tasks:
    - name: Check for Docker
      command: which docker
      register: docker_check
      ignore_errors: true

    #- name: Check for Docker Compose
    #  command: which docker compose
    #  register: compose_check
    #  ignore_errors: true

   # - debug: msg="{{ compose_check.stdout[1] }}"

    - name: Install Docker
      yum:
        name:
          - docker
          - docker-compose-plugin
        state: latest
      when: docker_check.rc != 0

   # - name: Docker Installation Step 1
   #   ansible.builtin.dnf:
   #     name: dnf-plugins-core
   #   when: docker_check.rc != 0

#    - name: Docker Installation Step 2
      # shell: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
#      command: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
 #     when: docker_check.rc != 0

    #- name: Add Docker packages repository
    #  ansible.builtin.yum_repository:
    #    name: docker-ce
    #    description: Docker YUM repo
    #    baseurl: https://download.docker.com/linux/fedora/docker-ce.repo
    #  when: docker_check.rc != 0

    #- name: Install Docker and related packages
    #  ansible.builtin.dnf:
    ##    name:
    #      - docker-ce
    #      - docker-ce-cli
    #      - containerd.io
    #      - docker-buildx-plugin
    #      - docker-compose-plugin
    #  when: docker_check.rc != 0

- name: johweserver Apache2 Container Setup
  hosts: johweb-ec2-pub1
  become: yes
  tasks:
    - name: Ensure Docker is running
      service:
        name: docker
        state: started
        enabled: yes
      when: docker_check.rc == 0

    - name: Start web server using docker compose
      community.docker.docker_compose_v2:
        project_src: /home/johith/johith-portfolio/webapp
      register: output
      when: docker_check.rc == 0
