- name: Install Utilities on johweserver
  hosts: johweb-ec2-pub1
  become: yes
  tasks:
    - name: Install wget
      yum:
        name: wget
        state: present
    - name: Install unzip
      yum:
        name: unzip
        state: present

- name: johweserver setup
  hosts: johweb-ec2-pub1
  become: yes
  tasks:
    - name: Install Apache Web Server
      yum:
        name: httpd
        state: present

    - name: Start Apache Web Server
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes

    - name: Download HTML files
      shell: wget https://www.tooplate.com/zip-templates/2106_soft_landing.zip
      args:
        chdir: /tmp

    - name: Unzip Toolplate HTML Files
      shell: unzip -o 2106_soft_landing.zip
      args:
        chdir: /tmp

    - name: Copy HTML files to webserver
      shell: cp -r 2106_soft_landing/* /var/www/html/
      args:
        chdir: /tmp

    - name: Restart Apache server
      ansible.builtin.service:
        name: httpd
        state: restarted
