services:
  johweb:
    image: 067771804697.dkr.ecr.us-east-2.amazonaws.com/johweb_docker_image_repo
    ports:
      - "8080:80"
    container_name: johweb
    volumes:
      - $PWD/johweb-content:/var/www/html

  caddy_reverse_proxy:
    container_name: caddyproxy
    image: caddy:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
