services:
  johweb:
    # build: .
    # image: johweb/webserver
    image: 067771804697.dkr.ecr.us-east-2.amazonaws.com/johweb_docker_image_repo
    ports:
      - "8080:80"
    container_name: johweb

  caddy_reverse_proxy:
    container_name: caddyproxy
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
