
name: "Johweb Ansible CaC Workflow"
on:
  workflow_dispatch:  # in future change this to 'pull_request'
    branches:
      - infra-staging
    paths:
      - ansible/main-playbook.yml
env:
  TF_VAR_THE_KEY: ${{ secrets.TF_VAR_THE_KEY }}
  WEBSRV_USR: ${{ vars.WEBSRV_USR }}
  ECR_ENDPOINT: ${{ vars.ECR_ENDPOINT }}
  HOST_IP: ${{ vars.HOST_IP }}

jobs:
  Ansible:
    name: "Run Anisble Playbook"
    runs-on: ubuntu-latest
    #defaults:
      #run:
     #   working-directory: ./ansible
    steps:

      - name: Install pip3
        run: sudo apt install python3-pip -y

      - name: Install Boto3
        run: pip3 install boto3

      #- name: Install Ansible
      #  run: 

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.TF_VAR_THE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Checkout Source Code
        uses: actions/checkout@v2
        with:
          ref: infra-staging # change to 'main' when push branch changes to 'pull_request'


      #- name: Run Ansible Playbook
      #  run: |
      #    ansible-playbook -i dynamic-inventory.py main-playbook.yml

      - name: Run Ansible Playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          key: ${{secrets.TF_VAR_THE_KEY}}
          directory: ./ansible
          playbook: main-playbook.yml
          options: |
            --inventory dynamic-inventory.py

          #inventory: |
          #  all:
          #   hosts:
          #     johweb-ec2-pub1:
          #        ansible_host: "{{ lookup('env', 'HOST_IP') }}"
          #        ansible_user: "{{ lookup('env', 'WEBSRV_USR') }}"
  Docker:
    needs: Ansible
    name: "Perform Docker Compose Up"
    runs-on: ubuntu-latest
    steps:

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.TF_VAR_THE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        env:
          PRIVATE_KEY: ${{ secrets.TF_VAR_THE_KEY }}

      - name: Checkout Source Code
        uses: actions/checkout@v2
        with:
          ref: infra-staging # change to 'main' when push branch changes to 'pull_request'

      - name: Directory checking
        run:  |
          ls -la
          ls -la webapp
          cat webapp/compose.yml

      - name: Copy Docker Compose File to EC2 instance
        run: |
          scp -o StrictHostKeyChecking=no webapp/compose.yml ${{vars.WEBSRV_USR}}@${{vars.HOST_IP}}:/home/${{vars.WEBSRV_USR}}/

      - name: Set permissions on Docker Compose file
        run: >
          ssh -o StrictHostKeyChecking=no
          ${{ vars.WEBSRV_USR }}@${{ vars.HOST_IP }}
          "sudo chown ${{ vars.WEBSRV_USR }}:${{ vars.WEBSRV_USR }}
          /home/${{ vars.WEBSRV_USR }}/compose.yml && sudo chmod 0644 /home/${{ vars.WEBSRV_USR }}/compose.yml"

      - name: Run Docker Compose
        run: >
          ssh -o StrictHostKeyChecking=no
          ${{ vars.WEBSRV_USR }}@${{ vars.HOST_IP }}
          "docker-compose -f /home/${{ vars.WEBSRV_USR }}/compose.yml up -d johweb"
