
name: "Johweb Ansible CaC Workflow"
on:
  workflow_dispatch:  # in future change this to 'pull_request'
    branches:
      - infra-staging
    paths:
      - ansible/main-playbook.yml
env:
  TF_VAR_THE_KEY: ${{ secrets.TF_VAR_THE_KEY }}
  WEBSRV_USR: ${{ vars.WEBSRV_USR }}
  ECR_ENDPOINT: ${{ vars.ECR_ENDPOINT }}
  HOST_IP: ${{ vars.HOST_IP }}

jobs:
  Ansible:
    name: "Run Anisble Playbook"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2
        with:
          ref: infra-staging # change to 'main' when push branch changes to 'pull_request'

      - name: Run Ansible Playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
<<<<<<< Updated upstream
          playbook: ansible/main-playbook.yml
=======
          directory: ./ansible
          playbook: main-playbook.yml
>>>>>>> Stashed changes
          key: ${{secrets.TF_VAR_THE_KEY}}
          inventory: |
            all:
              hosts:
                johweb-ec2-pub1:
                  ansible_host: "{{ lookup('env', 'HOST_IP') }}"
                  ansible_user: "{{ lookup('env', 'WEBSRV_USR') }}"
  Docker:
    name: "Perform Docker Compose Up"
    runs-on: ubuntu-latest
    steps:
      - name: Directory checking
        run:  |
          sudo ls -la /
          #ls -la webapp
          #cat webapp/compose.yml

      #- name: Allow usage of ssh-rsa algorithm
      #  run: echo "CASignatureAlgorithms +ssh-rsa" | sudo tee -a /etc/ssh/sshd_config

      #- name: Restart SSH Deamon
      #  run: sudo systemctl restart ssh.service

     # - name: Allow usage of ssh-rsa algorithm
     #   run: sudo cat "CASignatureAlgorithms +ssh-rsa" >> /etc/ssh/sshd_config

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.TF_VAR_THE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        env:
          PRIVATE_KEY: ${{ secrets.TF_VAR_THE_KEY }}

      - name: Checkout Source Code
        uses: actions/checkout@v2
        with:
          ref: infra-staging # change to 'main' when push branch changes to 'pull_request'

      - name: Directory checking
        run:  |
          ls -la
          ls -la webapp
          cat webapp/compose.yml

#      - name: Install SSH Client
#        run: sudo apt-get update && sudo apt-get install -y openssh-client

     # - name:  Copy Docker Compose File to EC2 instance
     #   uses: appleboy/scp-action@v0.1.7
     #   with:
     #     host: ${{vars.HOST_IP}}
     #     key: ${{secrets.TF_VAR_THE_KEY}}
     #     source: "webapp/compose.yml"
     #     target: /home/${{ vars.WEBSRV_USR }}/

      - name: Copy Docker Compose File to EC2 instance
        run: |
          scp -o StrictHostKeyChecking=no webapp/compose.yml ${{vars.WEBSRV_USR}}@${{vars.HOST_IP}}:/home/${{vars.WEBSRV_USR}}/

      - name: Set permissions on Docker Compose file
        run: >
          ssh -o StrictHostKeyChecking=no
          ${{ vars.WEBSRV_USR }}@${{ vars.HOST_IP }}
          "sudo chown ${{ vars.WEBSRV_USR }}:${{ vars.WEBSRV_USR }}
          /home/${{ vars.WEBSRV_USR }}/compose.yml && sudo chmod 0644 /home/${{ vars.WEBSRV_USR }}/compose.yml"

      - name: Run Docker Compose
        run: >
          ssh -o StrictHostKeyChecking=no
          ${{ vars.WEBSRV_USR }}@${{ vars.HOST_IP }}
          "docker-compose -f /home/${{ vars.WEBSRV_USR }}/compose.yml up -d"
