name: "Hygo Build Testing"

on:
  workflow_dispatch:  # in future change this to 'app-staging' branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: app-staging
          
      - name: "Setting up Hugo"
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.128.0'

      - name: "Building Hugo Site"
        working-directory: ./webapp/johweb-site
        run: hugo

      - name: "Listing files for the Hugo build"
        run: ls -la
