name: "Johweb Docker Image - ECR Upload Workflow. Only Triggered when app code changes"
on:
  workflow_call:

env:
  WEBSRV_USR: ${{ vars.WEBSRV_USR }}
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  #ECR_ENDPOINT: ${{ vars.ECR_ENDPOINT }}
  #AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}

jobs:
  docker_login:
    runs-on: ubuntu-latest
    steps:

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: app-staging
          path: webapp

      - name: Build and Push Image to Docker Hub
        uses: docker/build-push-action@v6
        with:
          context: webapp/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/johwebserver:latest

  #AWS_ECR:
  #  name: "Build, tag and push docker image to ECR"
  #  runs-on: ubuntu-latest
  #  steps:
  #  - name: Configure AWS Credentials
  #    uses: aws-actions/configure-aws-credentials@v1
  #    with:
  #      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #    aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #      aws-region: us-east-2

 #   - name: Checkout repo      
 #     uses: actions/checkout@v3
 #     with:
 #       ref: infra-staging

  #  - name: Login to Amazon ECR
  #    id: login-ecr
   #   uses: aws-actions/amazon-ecr-login@v2

   # - name: Build, tag, and push docker image to Amazon ECR
   #   working-directory: ./webapp
   #   env:
   #     REGISTRY: ${{ steps.login-ecr.outputs.registry }}
   #     REPOSITORY: johweb_docker_image_repo
   #     IMAGE_TAG: ${{ github.sha }}
   #   run: |
   #       docker build -t $REGISTRY/$REPOSITORY:latest .
    #      docker push $REGISTRY/$REPOSITORY:latest
